# Generated by Django 4.2.9 on 2024-01-20 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='address',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='empresa',
            name='sucursal_por_defecto',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cod_sunat', models.CharField(max_length=64, null=True)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('direccion', models.CharField(max_length=256, null=True)),
                ('descripcion', models.CharField(max_length=256, null=True)),
                ('nombre_contacto', models.CharField(max_length=256, null=True)),
                ('telefono_contacto', models.CharField(max_length=256, null=True)),
                ('correo_contacto', models.CharField(max_length=256, null=True)),
                ('almacen', models.UUIDField(default=uuid.uuid4, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
    ]
