# Generated by Django 4.2.9 on 2024-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_empresa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sucursal_por_defecto',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='almacen',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
