# Generated by Django 4.2.9 on 2024-01-25 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_empresapordefecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresapordefecto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
