# Generated by Django 4.2.9 on 2024-01-21 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('direccion', models.CharField(max_length=256, null=True)),
                ('telefono', models.CharField(max_length=256, null=True)),
                ('descripcion', models.CharField(max_length=256, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('codigo_sku', models.CharField(max_length=256, null=True)),
                ('unidad_medida', models.CharField(max_length=256, null=True)),
                ('descripcion', models.CharField(max_length=256, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ValorAtributoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=256, null=True)),
                ('Atributo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.atributoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionAtributoProductoTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_descontada', models.CharField(max_length=256, null=True)),
                ('catalogo_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.catalogosku')),
                ('variacion_atributo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.valoratributoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionAtributoProductoSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_descontada', models.CharField(max_length=256, null=True)),
                ('Variacion_atributo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.valoratributoproducto')),
                ('catalogo_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.catalogosku')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionAtributoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_unitario', models.CharField(max_length=256, null=True)),
                ('codigo_barra', models.CharField(max_length=64, null=True)),
                ('Atributo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.atributoproducto')),
                ('Valor_atributo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.valoratributoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('unidad_medida', models.CharField(max_length=256, null=True)),
                ('impuesto', models.CharField(max_length=256, null=True)),
                ('codigo_barra', models.CharField(max_length=64, null=True)),
                ('tipo_producto', models.CharField(max_length=256, null=True)),
                ('gestion_inventario', models.CharField(max_length=256, null=True)),
                ('Sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.subcategoria')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSkuStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.almacen')),
                ('catalogo_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.catalogosku')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSkuAlmacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('punto_reposicion', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.almacen')),
                ('catalogo_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.catalogosku')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='atributoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.producto'),
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
    ]
