# Generated by Django 4.2.9 on 2024-01-20 00:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('precio_por_volumen', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('cantidad_min_volumen', models.IntegerField(null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ALQUILADO', 'Alquilado'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], max_length=256)),
                ('categoria_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.categoria')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_atributo', models.CharField(max_length=256, null=True)),
                ('atributo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.atributo')),
                ('catalogo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.catalogo')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
    ]
