# Generated by Django 4.2.9 on 2024-01-20 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_atributo', models.CharField(max_length=256, null=True)),
                ('atributo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.atributo')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
        migrations.RenameModel(
            old_name='Catalogo',
            new_name='Producto',
        ),
        migrations.DeleteModel(
            name='AtributoCatalogo',
        ),
        migrations.AddField(
            model_name='atributoproducto',
            name='producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.producto'),
        ),
    ]
