# Generated by Django 4.2.9 on 2024-01-22 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_descontada', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Sub_categoria',
            new_name='sub_categoria',
        ),
        migrations.RenameField(
            model_name='valoratributoproducto',
            old_name='Atributo_producto',
            new_name='atributo_producto',
        ),
        migrations.RenameField(
            model_name='variacionatributoproducto',
            old_name='Atributo_producto',
            new_name='atributo_producto',
        ),
        migrations.RenameField(
            model_name='variacionatributoproducto',
            old_name='Valor_atributo_producto',
            new_name='valor_atributo_producto',
        ),
        migrations.RemoveField(
            model_name='variacionatributoproductosku',
            name='Variacion_atributo_producto',
        ),
        migrations.RemoveField(
            model_name='variacionatributoproductoterminal',
            name='cantidad_descontada',
        ),
        migrations.RemoveField(
            model_name='variacionatributoproductoterminal',
            name='catalogo_sku',
        ),
        migrations.AddField(
            model_name='catalogoskustock',
            name='cantidad_entrada',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='catalogoskustock',
            name='cantidad_salida',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='catalogoskustock',
            name='comentario',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='catalogoskustock',
            name='fecha_registro',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='variacionatributoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.producto'),
        ),
        migrations.AddField(
            model_name='variacionatributoproductoterminal',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='variacionatributoproductoterminal',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.terminal'),
        ),
        migrations.AlterField(
            model_name='catalogosku',
            name='codigo_sku',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.categoria'),
        ),
        migrations.AlterField(
            model_name='variacionatributoproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='variacionatributoproductoterminal',
            name='variacion_atributo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.variacionatributoproducto'),
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
        migrations.AddField(
            model_name='productoterminal',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.producto'),
        ),
        migrations.AddField(
            model_name='productoterminal',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.terminal'),
        ),
        migrations.AddField(
            model_name='productosku',
            name='catalogo_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.catalogosku'),
        ),
        migrations.AddField(
            model_name='productosku',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.producto'),
        ),
        migrations.AddField(
            model_name='variacionatributoproductosku',
            name='variacion_atributo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.variacionatributoproducto'),
        ),
    ]
