# Generated by Django 4.2.9 on 2024-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_atributoproducto_rename_catalogo_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributo',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='atributoproducto',
            old_name='atributo_id',
            new_name='atributo',
        ),
        migrations.RenameField(
            model_name='atributoproducto',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='atributoproducto',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
