# Generated by Django 4.2.9 on 2024-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
