# Generated by Django 4.2.9 on 2024-01-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_ubigeo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_doc',
            field=models.CharField(choices=[('0', 'SIN DEFINIR'), ('1', 'D.N.I'), ('6', 'R.U.C'), ('7', 'PASAPORTE')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
