# Generated by Django 4.2.9 on 2024-01-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cod_ubigeo_cliente_tipo_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_doc',
            field=models.CharField(choices=[('0', 'SIN DEFINIR'), ('1', 'D.N.I'), ('6', 'R.U.C'), ('7', 'PASAPORTE')], max_length=1, null=True),
        ),
    ]
