# Generated by Django 4.2.9 on 2024-01-24 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('descuento', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('fecha_alquiler', models.DateField(null=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('monto_garantia', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('monto_adelanto', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('direccion_evento', models.CharField(max_length=256, null=True)),
                ('es_una_reservacion', models.BooleanField(null=True)),
                ('fecha_entrega', models.DateField(null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.empresa')),
            ],
        ),
    ]
