# Generated by Django 4.2.9 on 2024-01-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='descuento',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='direccion_evento',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='es_una_reservacion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_alquiler',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_devolucion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='monto_adelanto',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='monto_garantia',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='monto_total',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
