# Generated by Django 4.2.9 on 2024-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_alquiler_cliente_id_alquiler_descuento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='alquiler',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
